version: "3.8"

services:
  db:
    image: postgres:13.1
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    container_name: web
    restart: always
    expose:
      - "8000"
    depends_on:
      - db
    volumes:
      - static_data:/code/static
    env_file:
      - ./.env
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:8000"
    depends_on:
      - web
    volumes:
      - static_data:/www/static/
      - ./nginx:/etc/nginx/conf.d

volumes:
  static_data:
  postgres_data:
